### ISSUE TITLE
Possible to write sources/target parser?

### ISSUE THREAD

**Issue by newhoggy** [pcapriotti/optparse-applicative#199] opened 2016-04-22 12:57 UTC
I tried to parse arguments typical for `cp`:

```
data Cmd
  = Copy    { recursive   :: Bool
            , sources     :: [String]
            , target      :: String
            }

copy :: Parser Cmd
copy = Copy
  <$>       (switch        ( long "recursive" ⊕ help "Recursive"))
  <*> many  (argument str  ( metavar "SOURCES"))
  <*>       (argument str  ( metavar "TARGET"))
```

But parser mistakes target as the last source:

```
22:48 $ ./dist/build/hw-files-cmd/hw-files-cmd cp src1 src2 target
Missing: TARGET

Usage: hw-files-cmd cp [--recursive] [SOURCES] TARGET
  Copy file(s)
```

Is there a way to encode this?

**Comment by HuwCampbell** [comment] 2016-04-26 00:56
Duplicate of #163, but in short, not really at this time. We don't have look aheads and the many arguments parser is greedy (as I said over there, it's like `let a = (,) <$> many anyChar <*> anyChar` in an applicative text parsers).

That said, in terms of not really adequate hacks, one can get the usage looking (close enough to) correct by constructing a list with `(:) <$> p1 <*> many p2`, then breaking it back apart again after parsing into the last element and the rest at the start.

**Comment by HuwCampbell** [comment] 2016-04-27 01:06
Closing this as it's a duplicate. Thanks for the report!

**Closed by HuwCampbell** 2016-04-27 01:06 UTC
