### ISSUE TITLE
Leading optional positional argument is parsed instead of required argument

### ISSUE THREAD

**Issue by matthewess** [pcapriotti/optparse-applicative#374] opened 2020-03-10 09:23 UTC
For background, I am trying to use `optparse-applicative` to implement an interface in the style of `httpie`, which allows users to make HTTP requests with an optional method argument, like so:

```bash
$ http google.com       # get google.com
$ http get google.com   # get google.com
$ http post google.com  # post google.com
```

I made an attempt at this, which I tried to reduce into a simple example:
```haskell
#! /usr/bin/env nix-shell
#! nix-shell -p "haskellPackages.ghcWithPackages (p: [p.optparse-applicative])
#! nix-shell -i runhaskell

module FirstArgOptional where

import           Options.Applicative

data Foo = Foo String String deriving Show

foo :: Parser Foo
foo = Foo <$> strArgument (metavar "FOO" <> value "foo") <*> strArgument
  (metavar "BAR")

data Foo' = Foo' (Maybe String) String deriving Show

foo' :: Parser Foo'
foo' = Foo' <$> optional (strArgument (metavar "FOO")) <*> strArgument
  (metavar "BAR")

main :: IO ()
main = print =<< execParser (info foo' idm)

-- shouldnt work
-- $ ./FirstArgOptional.hs
-- Missing: BAR

-- should work
-- $ ./FirstArgOptional.hs bar
-- Missing: BAR

-- works
-- $ ./FirstArgOptional.hs foo bar
-- Foo "foo" "bar" / Foo (Just "foo") "bar"
```

Neither method of tagging the leading argument as optional (`optional`/`value`) seems to work in convincing the parser that a single string should go to the second argument. Is this supported without having to move the optional argument after the required argument?

**Comment by matthewess** [comment] 2020-03-10 18:21
On the off chance anyone runs into the same issue, I am currently working around (albeit unsatisfactorily) by using a mutually exclusive set of `flag'`s for each "built in" method type and an `option` for custom methods, like

```bash
$ http-hs foo  # get foo
$ http-hs --get foo  # get foo
$ http-hs --put foo  # put foo
$ http-hs --method options foo  # options foo
```

**Comment by HuwCampbell** [comment] 2020-03-10 22:38
Indeed, this is similar to the many followed by one case. The issue is that parsers are greedy (you would also have this issue parser or similar).

I can think of a few possible solutions.

1) You could use a subparser for the methods.

So you would have subparsers with names `get`, `put`, `post`, each of which would have the options you needed as well.

Then at the top level, just have `subs <|> url`. The sub parser parser won't match urls, so they'll fall through to the argument parser.

2) Put the optional argument second and reshuffle them after they're both parsed. A bit unsatisfying, but should work well.

**Comment by matthewess** [comment] 2020-03-10 22:49
The issue with the first solution, as far as I can tell, is that there would need to be one "wildcard" subparser for custom methods like `http-hs PURGE example.com/queue`, to allow the tool to support services that use custom methods. 

As for solution 2, is this as easy as using the `<**>` combinator to reverse the order of the arguments?

**Comment by HuwCampbell** [comment] 2020-03-11 01:14
I was thinking something more like

```haskell
let flipper a b =
  case b of
    Just b' -> (Just a, b')
    Nothing -> (Nothing, a)
in
  flipper <$> strArgument (metavar "FOO") <*> optional (strArgument  (metavar "BAR"))
```

**Comment by matthewess** [comment] 2020-03-12 01:09
This was very close to fixing my issue! Unfortunately, there is another component to the CLI that must cause a similar situation: after the method and url are supplied, a user can supply 0 or more "request items" (key value pairs that get parsed into query string values, post body values, headers, etc depending on the separator used). It looks like this:

```bash
$ http-hs httpbin.org/get a==b
# GET httpbin.org/get?a=b
$ http-hs post httpbin.org/post foo=bar boolVal:=true fileContents:=@./file.json
# POST httpbin.org/post { "foo": "bar", "boolVal": true, "fileContents": { ... } }
```

Seems like its the same issue, where the greediness results in `flipper` gobbling up the first two of ANYTHING on the command line. Unfortunately, I can't think of a way to prevent the parser from seeing "request items" as a url or method, which are both parsed as plain strings. Request items have a custom Attoparsec based `ReadM`, but since the greedy parsers go first and don't have any way to discriminate, this doesn't do me any good.

Taking a look [here](https://github.com/jakubroztocil/httpie/blob/master/httpie/cli/argparser.py), httpie's command line parsers actually appears to use some relatively complex heuristics to disambiguate method/url/item parsing.

Spitballing here, but if I were trying to think of a way to do this in a more imperative/impure setting, my initial strategy would probably be to break the command-line up into words, reverse it, rebuild the command line backwards, parse request items greedily, then handle parsing the method+url by themselves. Such a strategy seems outside of the realm of possibilities using optparse-applicative.

The "grammar" for positional args is like: `http-hs [method] url [request-item ...]`. I wrote this reader:
```haskell
readMethod :: ReadM Text
readMethod = str >>= read' where
  read' s | T.all isAlpha s = return s
  read' _ = readerError "method must be consist of letters"
```
but this results in:
```bash
$ http-hs httpbin.org/get a==b
method must consist of letters
Usage ...
```

Any ideas for achieving an interface like this? Or is it too complicated/ambiguous to be described applicative-ly?

**Comment by HuwCampbell** [comment] 2021-01-09 11:00
Sorry I can't help more.

I'm going to close this issue as I don't want to push for better ways to write ambiguous / kind of weird parsers. A big part of _my_ goal for optparse is making best practice easy.

**Closed by HuwCampbell** 2021-01-09 11:00 UTC
