### ISSUE TITLE
Bug: `optional` combinator produces incorrect `--help` docs

### ISSUE THREAD

**Issue by ntc2** [pcapriotti/optparse-applicative#307] opened 2018-06-12 19:10 UTC
Consider the following simple program, which has two options, where it's legal to specify none or both of them, but not legal to specify just one of them:

``` haskell
import Options.Applicative

data Opts = Opts
  { b :: Maybe B
  } deriving Show

optsParser :: Parser Opts
optsParser = Opts
  <$> optional bParser

data B = B
  { b0 :: String
  , b1 :: String
  } deriving Show

bParser :: Parser B
bParser = B
  <$> strOption (long "b0")
  <*> strOption (long "b1")

main :: IO ()
main =
   print =<< execParser (info (helper <*> optsParser) fullDesc)
```

The help output incorrectly indicates that it's OK to specify just one of the options:

``` console
$ stack exec -- bug --help
Usage: bug [--b0 ARG] [--b1 ARG]
```

The correct usage would be `Usage: bug [--b0 ARG --b1 ARG]`, since just specifying one of the two options is not allowed. Indeed, running the program and specifying just one of the options is an error:

``` console
$ stack exec -- bug       
Opts {b = Nothing}
$ stack exec -- bug --b0 0 --b1 1
Opts {b = Just (B {b0 = "0", b1 = "1"})}
$ stack exec -- bug --b0 0       
Missing: --b1 ARG

Usage: bug [--b0 ARG] [--b1 ARG]
```

I believe this issue is closely related to Issue #220.

**Comment by HuwCampbell** [comment] 2018-06-13 11:51
Yep, this is a duplicate of #220.

The tree structure we currently use for pretty printing the command line simplifies what's optional and has multiplicity to the level of each option. It's this way because it's actually quite complex tracking this in the tree and getting the pretty printing right.

No excuse though, it should be fixed.

**Comment by benjaminselfridge** [comment] 2019-03-03 22:44
@HuwCampbell I'm working on a patch for this right now. There's a chance I won't finish it, but I wanted to note this here to in case you wanted to avoid duplicate efforts.

**Closed** 2019-03-15 09:37 UTC

**Comment by ntc2** [comment] 2019-03-15 16:44
Thanks Ben!
