### ISSUE TITLE
Allow merged flags

### ISSUE THREAD

**Issue by mrak** [pcapriotti/optparse-applicative#129] opened 2015-02-21 23:18 UTC
I can't find a way for two switches to be specified together:

```sh
# works
$ program -a -b
# fails
$ program -ab
```

where

```haskell
aFlag :: Parser Bool
aFlag = switch (short 'a' <> help "a flag")

bFlag :: Parser Bool
bFlag = switch (short 'b' <> help "b flag")
```

The intent is that both `aFlag` and `bFlag` will be parsed as `True`

**Comment by pcapriotti** [comment] 2015-02-21 23:22
Duplicate of #123 .

**Closed by pcapriotti** 2015-02-21 23:22 UTC
