### ISSUE TITLE
Support for parsing RawFilePath

### ISSUE THREAD

**Issue by zouppen** [pcapriotti/optparse-applicative#449] opened 2022-03-14 20:09 UTC
Some Haskell libraries use RawFilePath such as [hinotify](https://hackage.haskell.org/package/hinotify-0.4.1) which uses "system encoding", which is often (but not always?) UTF-8.

RawFilePath is a type alias for strict ByteString and optparse-applicative can technically parse it with `strOption` but causes encoding issues if the parameter contains non-ASCII characters and the resulting file name doesn't have the correct byte sequence.

I'm not sure how to implement it, but a naive implementation of "rawFilePathOption" for it would be to first parse it as a Text (or String) and then encode it to ByteString to system's default encoding, whatever that is.

In case you need clarification, I'm happy to provide a minimal example.

**Comment by pcapriotti** [comment] 2022-03-21 19:30
This is more or less a duplicate of #65. In particular, the last comment there by luke-clifton should have all the information you need to be able to extract `RawFilePath`s from command line arguments. I'll close this issue, but feel free to reopen if that's not enough for your use case.

**Closed by pcapriotti** 2022-03-21 19:30 UTC
