### ISSUE TITLE
Broken links on Hackage

### ISSUE THREAD

**Issue by yaitskov** [pcapriotti/optparse-applicative#383] opened 2020-05-08 00:18 UTC
Hi,

On page
http://hackage.haskell.org/package/optparse-applicative

Links below Table of contents are dangling.
Example: 
http://hackage.haskell.org/package/optparse-applicative-0.15.1.0/optparse-applicative-0.15.1.0/src#introduction

Page not found

**Comment by HuwCampbell** [comment] 2020-05-08 03:43
Duplicate of #328 and #297.

This is a known bug in Hackage's markdown renderer.

See https://github.com/haskell/hackage-server/issues/650
and https://github.com/jgm/cheapskate/issues/24

**Closed by HuwCampbell** 2020-05-08 03:43 UTC
